# Generated by Django 5.1 on 2024-08-25 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 25, 9, 59, 54, 348689, tzinfo=datetime.timezone.utc)),
        ),
    ]
